# -*- coding: utf-8 -*-
"""Madhya Pradesh_Beds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QfxENZ9VMZZMqq5gchfsI9UkvMqMIX9Z
"""

import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from time import sleep

HospitalName=[]
Map=[]
BedStatus=[]
IsolationBeds=[]
OxygenSupported=[]
ICUavailable=[]
last_updated=[]

for page in range(1,7):
  url="http://sarthak.nhmmp.gov.in/covid/facility-bed-occupancy-details/?show=200&pagenum="+str(page)+"&district_id=0&facility_org_type=0&facility=0"
  r=requests.get(url)
  page=r.content
  soup=BeautifulSoup(page,'html.parser')
  row=soup.find_all('td')
  hospitalname=soup.find_all('div',{'class':"hospitalname"})
  for hospital in hospitalname:
    HospitalName.append(hospital.text)
  ##  print(HospialName)

  ## ref=soup.find_all("a",{'class':'btn btn-primary btn-sm'})
  ref=soup.find_all("a",{'style':"text-transform: uppercase;text-align: left"})
  for href in ref:
    map=href.attrs['href'] if href is not None else ' '
    Map.append(map)
    # print(Map)

  BedStats=soup.find_all("span",{'class':"badge bed-status"})
  for bed in BedStats:
    Bedstatus=bed.text if bed is not None else " "
    BedStatus.append(Bedstatus)
    ## print(BedStatus)

  desc=soup.find_all("div",{'class':"deecriptions"})
  for numbers in desc:
    # num=numbers.find_all("label")[0]
    # nums=numbers.find_all("label")[1]

    num=numbers.find_all('li')[0]
    num_t=num.text.split('\n')
    IsolationBeds.append(num_t[2])
    # #print(IsolationBeds)

    num_o=numbers.find_all('li')[1]
    num_oxy=num_o.text.split('\n')
    OxygenSupported.append(num_oxy[2])
    ##print(OxygenSupported)
    
    icu=numbers.find_all("li")[2]
    num_icu=icu.text.split('\n')
    ICUavailable.append(num_icu[2])
    # # print(ICUavailable)

    last=soup.find("div",class_="last-updated")
    last_update=last.text.split('\r\n')
    last_updated.append(last_update[1])
    # # print(last_updated)

print(len(HospitalName), len(Map), len(BedStatus),len(IsolationBeds),len(OxygenSupported),len(ICUavailable),len(last_updated))
mp_bedlist=pd.DataFrame({"Hospital Name":HospitalName,"Map Link":Map,"Bed Status":BedStatus,"No. of Isolation Beds":IsolationBeds,"Oxygen Suppoeted":OxygenSupported,"ICU":ICUavailable,"Last Updated":last_updated})
## "Last Updated":last_updated

mp_bedlist

mp_bedlist.to_excel('MadhyaPradesh_cowinmap.xlsx')