# -*- coding: utf-8 -*-
"""kovaicare.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MITNm0miIbed3ted5ybt_EG0rs7a1yFL
"""

import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import html5lib

HospitalName=[]
TotalBeds=[]
VacantBeds=[]
OccupiedBeds=[]
MoreDetailsLink=[]
GeneralBeds=[]
OxygenBeds=[]
VentilatorBeds=[]
last_updated=[]
last=[]
G_name=[]
G_Tbed=[]
G_Obed=[]
G_Xbed=[]
O_name=[]
O_Tbed=[]
O_Obed=[]
O_Xbed=[]
V_name=[]
V_Tbed=[]
V_Obed=[]
V_Xbed=[]

url="http://kovaicare-ccmc.com/"
r=requests.get(url)
page=r.content
soup=BeautifulSoup(page,'html.parser')
line=soup.find_all('td')
count=0
for low in line:
  # print(low.text)
  up=low.text.split("\n\n")
  # print(up)
  # print(len(up))
  if len(up)==1:
    if(len(str(up)))==23:
      if (str(up))!="['Ventilator/ICU Beds']":
        if(count==38):
          last_updated.append("['0']")
          last_updated.append(up)
          count+=1
        else:
          last_updated.append(up)
          count+=1
# last.append(last_updated)
        # last_updated.append(up)
# print(last_updated)
      # print(len(str(up)))


row=soup.find_all('td',{'style':"color:black;"})
# ## print(row)

for hospi in row:
  hospital=hospi.text.split('\r\n')
  # print(hospital[1])
  HospitalName.append(hospital[1])
# ### print(HospitalName)

bar=soup.find_all('div',{'class':"progress-bar bg-success"})
# # print(bar)
for vac in bar:
  vacant=vac.text.split('\r\n')
  # print(vacant)
  VacantBeds.append(vacant[1])
#   # print(VacantBeds)

bar_o=soup.find_all('div',{'class':"progress-bar bg-warning"})
# # print(bar_o)
for occu in bar_o:
  occupied=occu.text.split('\r\n')
  OccupiedBeds.append(occupied[1])
##   print(OccupiedBeds)

ref=soup.find_all('td')
# print(ref)
for href in ref:
  l=href.find('a')
  if l is not None:
    link=url+l['href']
    MoreDetailsLink.append(link)
    # # print(link)
    r=requests.get(link)
    p_content=r.content
    bs=BeautifulSoup(p_content,'html.parser')
    colume=bs.find_all('div',{'class':"card bg-c-blue order-card"})
    for i in colume:
      col=i.find('span').text
      TotalBeds.append(col)
      # print(col)
    gen=bs.find_all("div",{"class":"card statustic-card"})
    general=[]
    temp=[]
  
    count=0
    for j in gen:
      # print(j.text)
      prim=j.text.split("\n\n")
      # prime=prim[1].split("\n\n")
      # print(prime)
      count+=1
      lprime=prim[1].split("\n")
      if (count==1):
        G_name.append(lprime[0])
        G_Tbed.append(lprime[2])
        G_Obed.append(lprime[3])
        G_Xbed.append(lprime[4])
      elif (count==2):
        O_name.append(lprime[0])
        O_Tbed.append(lprime[2])
        O_Obed.append(lprime[3])
        O_Xbed.append(lprime[4])
      else:
        V_name.append(lprime[0])
        V_Tbed.append(lprime[2])
        V_Obed.append(lprime[3])
        V_Xbed.append(lprime[4])
      # print(lprime)
      # print(count)
      # general.append(prime)
      # print(general)
    # GeneralBeds.append(general[0])
    # OxygenBeds.append(general[1])
    # VentilatorBeds.append(general[2])
    # Details.append(general)
    # print(Details)

print(len(HospitalName), len(TotalBeds),len(OccupiedBeds), len(VacantBeds),len(MoreDetailsLink),len(GeneralBeds),len(OxygenBeds),len(VentilatorBeds),len(last_updated),len(G_name),
    len(G_Tbed),
    len(G_Obed),
    len(G_Xbed),
    len(O_name),
    len(O_Tbed),
    len(O_Obed),
    len(O_Xbed),
    len(V_name),
    len(V_Tbed),
    len(V_Obed),
    len(V_Xbed))

kovaicare=pd.DataFrame({"Hospital Name":HospitalName,"Total No. of Beds":TotalBeds,"No. of Occupied Beds":OccupiedBeds,"No. of Vacant Beds":VacantBeds,"General Beds":G_name,
"Total no. of General Beds":G_Tbed,
"Occupied General Beds":G_Obed,
"Vacant General Beds":G_Xbed,
"Oxygen Beds":O_name,
"Total no. of Oxygen Beds":O_Tbed,
"Occupied Oxygen Beds":O_Obed,
"Vacant Oxygen Beds":O_Xbed,
"Ventilator Beds":V_name,
"Total no. of Ventilator Beds":V_Tbed,
"Occupied Ventilator Beds":V_Obed,
"Vacant Ventilator Beds":V_Xbed,"For more detail...Click on link":MoreDetailsLink,"Last Updated":last_updated,})

kovaicare

kovaicare.to_excel('kovaicare_cowinmap.xlsx')

# http://kovaicare-ccmc.com/
# http://kovaicare-ccmc.com/viewhospitaluser.php?uid=20