# -*- coding: utf-8 -*-
"""One more source for Cbe #11_kovaicare.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MITNm0miIbed3ted5ybt_EG0rs7a1yFL
"""

import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import html5lib

HospitalName=[]
TotalBeds=[]
VacantBeds=[]
OccupiedBeds=[]
MoreDetailsLink=[]
GeneralBeds=[]
OxygenBeds=[]
VentilatorBeds=[]
last_updated=[]

url="http://kovaicare-ccmc.com/"
r=requests.get(url)
page=r.content
soup=BeautifulSoup(page,'html.parser')
line=soup.find_all('td')
count=0
for low in line:
  # print(low.text)
  up=low.text.split("\n\n")
  # print(up)
  # print(len(up))
  if len(up)==1:
    if(len(str(up)))==23:
      if (str(up))!="['Ventilator/ICU Beds']":
        if(count==38):
          last_updated.append("['0']")
          last_updated.append(up)
          count+=1
        else:
          last_updated.append(up)
          count+=1
        # last_updated.append(up)
# print(last_updated)
      # print(len(str(up)))


row=soup.find_all('td',{'style':"color:black;"})
# ## print(row)

for hospi in row:
  hospital=hospi.text.split('\r\n')
  # print(hospital[1])
  HospitalName.append(hospital[1])
# ### print(HospitalName)

bar=soup.find_all('div',{'class':"progress-bar bg-success"})
# # print(bar)
for vac in bar:
  vacant=vac.text.split('\r\n')
  # print(vacant)
  VacantBeds.append(vacant[1])
#   # print(VacantBeds)

bar_o=soup.find_all('div',{'class':"progress-bar bg-warning"})
# # print(bar_o)
for occu in bar_o:
  occupied=occu.text.split('\r\n')
  OccupiedBeds.append(occupied[1])
##   print(OccupiedBeds)

ref=soup.find_all('td')
# print(ref)
for href in ref:
  l=href.find('a')
  if l is not None:
    link=url+l['href']
    MoreDetailsLink.append(link)
    # # print(link)
    r=requests.get(link)
    p_content=r.content
    bs=BeautifulSoup(p_content,'html.parser')
    colume=bs.find_all('div',{'class':"card bg-c-blue order-card"})
    for i in colume:
      col=i.find('span').text
      TotalBeds.append(col)
      # print(col)
    gen=bs.find_all("div",{"class":"card statustic-card"})
    general=[]
    temp=[]
    for j in gen:
      # print(j.text)
      prim=j.text.split("\n\n")
      prime=prim[1].split("\n\n")
      # print(prime)
      general.append(prime)
      # print(general)
    GeneralBeds.append(general[0])
    OxygenBeds.append(general[1])
    VentilatorBeds.append(general[2])
    # Details.append(general)
    # print(Details)

print(len(HospitalName), len(TotalBeds),len(OccupiedBeds), len(VacantBeds),len(MoreDetailsLink),len(GeneralBeds),len(OxygenBeds),len(VentilatorBeds),len(last_updated))

kovaicare=pd.DataFrame({"Hospital Name":HospitalName,"Total No. of Beds":TotalBeds,"No. of Occupied Beds":OccupiedBeds,"No. of Vacant Beds":VacantBeds,"No. of General Beds":GeneralBeds,"No. of Oxygen Beds":OxygenBeds,"No. of Ventilator Beds":VentilatorBeds,"For more detail...Click on link":MoreDetailsLink,"Last Updated":last_updated})

kovaicare

kovaicare.to_excel('kovaicare_cowinmap.xlsx')

# http://kovaicare-ccmc.com/
# http://kovaicare-ccmc.com/viewhospitaluser.php?uid=20